swagger: '2.0'
info:
  title: Project Spiderweb Service
  description: |
    # Introduction
    This is the official internal API documentation for the Project Spiderweb Service.
  contact:
    name: Austin Glenn
  version: 1.0.0
host: NA
basePath: /api
schemes:
- https
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  'Local Development':
    type: basic
    description: |
      When hitting a local run of the service, you may bypass security and instead pass in the following headers:
      * **X-USER-ID**: the user that you want to behave as.
security:
  - 'Local Development': []
parameters:
  'pageIdPath':
    name: pageId
    in: path
    description: |
      ID of the associated page.

      **Example**: `PG_123456789012345`
    required: true
    type: string
  'detailIdPath':
    name: detailId
    in: path
    description: |
      ID of the associated detail.

      **Example**: `DT_123456789012345`
    required: true
    type: string
  'pageBody':
    name: detailObject
    in: body
    required: true
    schema:
      $ref: 'pages.yaml#/definitions/page'
  'detailBody':
    name: detailObject
    in: body
    required: true
    schema:
      $ref: 'pages.yaml#/definitions/pageDetail'
responses:
  'success':
    description: Success
    schema:
      type: object
      required:
      - meta
      properties:
        meta:
          $ref: '#/definitions/meta'
definitions:
  'meta':
    example:
      httpStatus: '200 - OK'
    type: object
    required:
    - httpStatus
    - requestId
    properties:
      httpStatus:
        type: string
        description: |
          Always of the format `{X} - {Y}`,
          where `{X}` is the associated HTTP status code,
          and `{Y}` is a human readable explanation of the status code.
      error:
        type: object
        description: Only given if an error occurred during the request.
        required:
        - errorMessage
        - errorCode
        properties:
          errorMessage:
            type: string
            description: A human readable explanation of the error.
          errorCode:
            type: string
            description: An identifying code associated with the error.
      requestId:
        type: string
        description: A transaction id associated with the request.
paths:
  /pages/{pageId}/full:
    get:
      tags:
      - full page
      summary: Get Entire Page
      description: Get the provided page, including properties, details, relations, etc.
      operationId: getEntirePage
      parameters:
      - $ref: '#/parameters/pageIdPath'
      responses:
        '200':
          description: Page Object
          schema:
            type: object
            required:
            - result
            - meta
            properties:
              result:
                $ref: 'pages.yaml#/definitions/pageFull'
              meta:
                $ref: '#/definitions/meta'
  /pages:
    post:
      tags:
      - page
      summary: Create Page
      description: Creates a new page.
      operationId: createPage
      parameters:
      - $ref: '#/parameters/pageBody'
      responses:
        '200':
          description: Page ID
          schema:
            type: object
            required:
            - result
            - meta
            properties:
              result:
                type: object
                required:
                - id
                properties:
                  id:
                    $ref: 'pages.yaml#/definitions/pageId'
              meta:
                $ref: '#/definitions/meta'
  /pages/{pageId}:
    get:
      tags:
      - page
      summary: Get Page
      description: Get the provided page.
      operationId: getPage
      parameters:
      - $ref: '#/parameters/pageIdPath'
      responses:
        '200':
          description: Page Object
          schema:
            type: object
            required:
            - result
            - meta
            properties:
              result:
                $ref: 'pages.yaml#/definitions/page'
              meta:
                $ref: '#/definitions/meta'
    put:
      tags:
      - page
      summary: Set Page
      description: Sets the provided page.
      operationId: setPage
      parameters:
      - $ref: '#/parameters/pageIdPath'
      - $ref: '#/parameters/pageBody'
      responses:
        '200':
          $ref: '#/responses/success'
    delete:
      tags:
      - page
      summary: Remove Page
      description: Removes the provided page from all queries.
      operationId: removePage
      parameters:
      - $ref: '#/parameters/pageIdPath'
      responses:
        '200':
          $ref: '#/responses/success'
  /pages/{pageId}/details:
    get:
      tags:
      - detail
      summary: Get Page Details
      description: Get the provided page's details, in order.
      operationId: getPageDetails
      parameters:
      - $ref: '#/parameters/pageIdPath'
      responses:
        '200':
          description: Page Details List
          schema:
            type: array
            items:
            - $ref: 'pages.yaml#/definitions/pageDetail'
    post:
      tags:
      - detail
      summary: Create Page Detail
      description: Creates a new detail for the provided page.
      operationId: createPageDetail
      parameters:
      - $ref: '#/parameters/pageIdPath'
      - $ref: '#/parameters/detailBody'
      responses:
        '200':
          description: Page Detail ID
          schema:
            type: object
            required:
            - result
            - meta
            properties:
              result:
                type: object
                required:
                - id
                properties:
                  id:
                    $ref: 'pages.yaml#/definitions/pageDetailId'
              meta:
                $ref: '#/definitions/meta'
  /pages/{pageId}/details/{detailId}:
    get:
      tags:
      - detail
      summary: Get Page Detail
      description: Sets the provided detail for the provided page.
      operationId: getPageDetail
      parameters:
      - $ref: '#/parameters/pageIdPath'
      - $ref: '#/parameters/detailIdPath'
      responses:
        '200':
          description: Page Detail Object
          schema:
            type: object
            required:
            - result
            - meta
            properties:
              result:
                $ref: 'pages.yaml#/definitions/pageDetail'
              meta:
                $ref: '#/definitions/meta'
    put:
      tags:
      - detail
      summary: Set Page Detail
      description: Sets the provided detail for the provided page.
      operationId: setPageDetail
      parameters:
      - $ref: '#/parameters/pageIdPath'
      - $ref: '#/parameters/detailIdPath'
      - $ref: '#/parameters/detailBody'
      responses:
        '200':
          $ref: '#/responses/success'
    delete:
      tags:
      - detail
      summary: Remove Page Detail
      description: Removes the provided page's detail from all queries.
      operationId: removePageDetail
      parameters:
      - $ref: '#/parameters/pageIdPath'
      - $ref: '#/parameters/detailIdPath'
      responses:
        '200':
          $ref: '#/responses/success'